# Generated by Django 5.1.3 on 2025-01-16 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appy', '0002_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Products'},
        ),
    ]
