# Generated by Django 5.1.3 on 2025-01-16 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appy', '0003_alter_product_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
        migrations.AlterModelOptions(
            name='products',
            options={},
        ),
    ]
